[pytest]
testpaths =
    crm-extension/tests
    tests
pythonpath =
    .
    chitu-connector
addopts =
    --import-mode=prepend
python_files = test_*.py
python_classes = Test*
python_functions = test_*
