<?php
/**
 * Phase3B05-C — EmailEvent → SalesFeedback bridge.
 *
 * Creates one SalesFeedback per EmailEvent (idempotent via externalFeedbackId).
 * LearningSignal is generated by the existing Phase3B04 SalesFeedbackLearningSignalHook.
 * Does not modify EmailEvent contract fields or train AI models.
 */

namespace Espo\Custom\Hooks\EmailEvent;

use Espo\Core\Hook\Hook\AfterSave;
use Espo\ORM\Entity;
use Espo\ORM\EntityManager;
use Espo\ORM\Repository\Option\SaveOptions;

class EmailEventSalesFeedbackHook implements AfterSave
{
    public static int $order = 30;

    /** @var array<string, array{0: string, 1: string}> */
    private const EVENT_FEEDBACK_MAP = [
        'REPLIED' => ['CUSTOMER_REPLY', 'NEUTRAL'],
        'CLICKED' => ['EMAIL_INTERESTED', 'POSITIVE'],
        'BOUNCED' => ['EMAIL_BOUNCED', 'NEGATIVE'],
    ];

    public function __construct(private EntityManager $entityManager) {}

    public function afterSave(Entity $event, SaveOptions $options): void
    {
        if (!$event->isNew()) {
            return;
        }

        $eventType = (string) $event->get('eventType');
        if (!isset(self::EVENT_FEEDBACK_MAP[$eventType])) {
            return;
        }

        $leadId = $event->get('leadId');
        $eventId = $event->getId();
        if (!$leadId || !$eventId) {
            return;
        }

        $lead = $this->entityManager->getEntityById('Lead', $leadId);
        if (!$lead) {
            return;
        }

        $externalFeedbackId = 'email-event:' . $eventId;
        $existing = $this->entityManager->getRDBRepository('SalesFeedback')
            ->where(['externalFeedbackId' => $externalFeedbackId])
            ->findOne();
        if ($existing) {
            return;
        }

        [$feedbackType, $outcome] = self::EVENT_FEEDBACK_MAP[$eventType];
        $feedback = $this->entityManager->getEntity('SalesFeedback');
        $feedback->set([
            'name' => 'Email Feedback: ' . $feedbackType . ' - ' . ($lead->get('name') ?: $leadId),
            'leadId' => $leadId,
            'externalLeadId' => $lead->get('peCandidateId'),
            'externalFeedbackId' => $externalFeedbackId,
            'feedbackType' => $feedbackType,
            'outcome' => $outcome,
            'reason' => 'Derived from EmailEvent ' . $eventType,
            'note' => 'email_event_id=' . $eventId . '; message_id=' . (string) $event->get('externalMessageId'),
            'product' => $lead->get('peBestFirstProduct'),
            'campaign' => $event->get('campaign'),
            'source' => 'EMAIL_EVENT',
            'feedbackAt' => $event->get('eventAt'),
            'assignedUserId' => $lead->get('assignedUserId'),
        ]);
        $this->entityManager->saveEntity($feedback);
    }
}
